---
- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure
  changed_when: true
  listen: "reconfigure gitlab"

- name: Restart GitLab
  ansible.builtin.command: gitlab-ctl restart
  changed_when: true
  listen: "restart gitlab"
