apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Core cluster platform services (Istio, Prometheus, Kyverno, ESO)
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: istio-system
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: kyverno
    - server: https://kubernetes.default.svc
      namespace: external-secrets
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
