apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-services
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "0.9.11"
      helm:
        valueFiles:
          - $values/apps/cluster-services/external-secrets/base/values.yaml
          - $values/apps/cluster-services/external-secrets/overlays/prod/values.yaml
    - repoURL: https://github.com/<org>/<repo>.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
